### ISSUE TITLE
One small thing...

### ISSUE THREAD

**Issue by bensullivan8** [bensullivan8/content-page#1]
The only problem that I've been stuck trying to fix for the past couple of days is that the cite beneath the poem/song near the beginning of the page is lower than markbot expects it to be. I've been trying my best to find a way around the issue and the website passes the visual aspect if I change the cite tag to a p tag, but then markbot won't pass me because it doesn't meet the requirement of having "blockquote>footer>cite". 
So I'm stuck and not sure if this is an error on my end or just markbot having an issue with trying to mark it when I'm using a newer Mac. Any ideas?

Thanks,
Ben Sullivan

@muxlowc

**Comment by muxlowc** [comment]
Hey @bensullivan8 

So what marbot wants is to have a cite (so in this case its the title of the song, because that's what's being cited in the song/poem above).. and technically the cite in this case is fairly important but secondary information to the poem, so therefore the cite has to go into a footer (only the cite needs to be in the footer, not the p tag (so you were very close!)

`    <blockquote class="italic milli push-2">
      <p class="push-0">Believe green buds awaken in the spring,<br>That autumn paints the leaves with somber fire;<br>Believe I held my heart inviolate<br>To lavish on one man my hot desire.</p>
      <footer class="micro not-italic">— <cite class="not-italic">The Song of Bélit</cite></footer>
    </blockquote>`

If you look at the code above, you can see that the cite is the only thing inside of the footer, and the class of micro should be on the footer and not the cite (in reality you can put it on either, but markbot prefers it on the footer).

Hope this helps! Let me know if it's still not letting you pass!

Thanks,
Christina

**Comment by muxlowc** [comment]
@bensullivan8  can you please close this issue if you got it sorted out?

Thanks!
